#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDOrganizacionLaboratoriosDAI")]
	public partial class conexionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTUsuario1(TUsuario1 instance);
    partial void UpdateTUsuario1(TUsuario1 instance);
    partial void DeleteTUsuario1(TUsuario1 instance);
    partial void InsertTAsignatura(TAsignatura instance);
    partial void UpdateTAsignatura(TAsignatura instance);
    partial void DeleteTAsignatura(TAsignatura instance);
    partial void InsertTDia(TDia instance);
    partial void UpdateTDia(TDia instance);
    partial void DeleteTDia(TDia instance);
    partial void InsertTDocente(TDocente instance);
    partial void UpdateTDocente(TDocente instance);
    partial void DeleteTDocente(TDocente instance);
    partial void InsertTDocente_Asignatura(TDocente_Asignatura instance);
    partial void UpdateTDocente_Asignatura(TDocente_Asignatura instance);
    partial void DeleteTDocente_Asignatura(TDocente_Asignatura instance);
    partial void InsertTHorario(THorario instance);
    partial void UpdateTHorario(THorario instance);
    partial void DeleteTHorario(THorario instance);
    partial void InsertTLaboratorio(TLaboratorio instance);
    partial void UpdateTLaboratorio(TLaboratorio instance);
    partial void DeleteTLaboratorio(TLaboratorio instance);
    partial void InsertTPerfil(TPerfil instance);
    partial void UpdateTPerfil(TPerfil instance);
    partial void DeleteTPerfil(TPerfil instance);
    partial void InsertTUsuario(TUsuario instance);
    partial void UpdateTUsuario(TUsuario instance);
    partial void DeleteTUsuario(TUsuario instance);
    #endregion
		
		public conexionDataContext() : 
				base(global::Modelo.Properties.Settings.Default.BDOrganizacionLaboratoriosDAIConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public conexionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TPrincipal> TPrincipal
		{
			get
			{
				return this.GetTable<TPrincipal>();
			}
		}
		
		public System.Data.Linq.Table<TUsuario1> TUsuario1
		{
			get
			{
				return this.GetTable<TUsuario1>();
			}
		}
		
		public System.Data.Linq.Table<TAsignatura> TAsignatura
		{
			get
			{
				return this.GetTable<TAsignatura>();
			}
		}
		
		public System.Data.Linq.Table<TDia> TDia
		{
			get
			{
				return this.GetTable<TDia>();
			}
		}
		
		public System.Data.Linq.Table<TDocente> TDocente
		{
			get
			{
				return this.GetTable<TDocente>();
			}
		}
		
		public System.Data.Linq.Table<TDocente_Asignatura> TDocente_Asignatura
		{
			get
			{
				return this.GetTable<TDocente_Asignatura>();
			}
		}
		
		public System.Data.Linq.Table<THorario> THorario
		{
			get
			{
				return this.GetTable<THorario>();
			}
		}
		
		public System.Data.Linq.Table<TLaboratorio> TLaboratorio
		{
			get
			{
				return this.GetTable<TLaboratorio>();
			}
		}
		
		public System.Data.Linq.Table<TPerfil> TPerfil
		{
			get
			{
				return this.GetTable<TPerfil>();
			}
		}
		
		public System.Data.Linq.Table<TPerfil_Usuario> TPerfil_Usuario
		{
			get
			{
				return this.GetTable<TPerfil_Usuario>();
			}
		}
		
		public System.Data.Linq.Table<TPrincipal1> TPrincipal1
		{
			get
			{
				return this.GetTable<TPrincipal1>();
			}
		}
		
		public System.Data.Linq.Table<TUsuario> TUsuario
		{
			get
			{
				return this.GetTable<TUsuario>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spuTDocente_Actualizar")]
		public ISingleResult<spuTDocente_ActualizarResult> spuTDocente_Actualizar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodDocente", DbType="VarChar(5)")] string codDocente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(100)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codDocente, nombre);
			return ((ISingleResult<spuTDocente_ActualizarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spuTDocente_Listar")]
		public ISingleResult<spuTDocente_ListarResult> spuTDocente_Listar()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spuTDocente_ListarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spuTDocente_Insertar")]
		public ISingleResult<spuTDocente_InsertarResult> spuTDocente_Insertar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodDocente", DbType="VarChar(5)")] string codDocente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(100)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codDocente, nombre);
			return ((ISingleResult<spuTDocente_InsertarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spuTAsignatura_Actualizar")]
		public ISingleResult<spuTAsignatura_ActualizarResult> spuTAsignatura_Actualizar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodAsignatura", DbType="VarChar(12)")] string codAsignatura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreAsignatura", DbType="VarChar(40)")] string nombreAsignatura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Creditos", DbType="VarChar(20)")] string creditos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Categoria", DbType="VarChar(20)")] string categoria)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codAsignatura, nombreAsignatura, creditos, categoria);
			return ((ISingleResult<spuTAsignatura_ActualizarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spuTAsignatura_Insertar")]
		public ISingleResult<spuTAsignatura_InsertarResult> spuTAsignatura_Insertar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodAsignatura", DbType="VarChar(12)")] string codAsignatura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreAsignatura", DbType="VarChar(40)")] string nombreAsignatura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Creditos", DbType="VarChar(20)")] string creditos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Categoria", DbType="VarChar(20)")] string categoria)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codAsignatura, nombreAsignatura, creditos, categoria);
			return ((ISingleResult<spuTAsignatura_InsertarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spuTDocenteAsignatura_Actualizar")]
		public ISingleResult<spuTDocenteAsignatura_ActualizarResult> spuTDocenteAsignatura_Actualizar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodDocente_Asignatura", DbType="VarChar(12)")] string codDocente_Asignatura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodDocente", DbType="VarChar(5)")] string codDocente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodAsignatura", DbType="VarChar(12)")] string codAsignatura)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codDocente_Asignatura, codDocente, codAsignatura);
			return ((ISingleResult<spuTDocenteAsignatura_ActualizarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spuTDocenteAsignatura_Insertar")]
		public ISingleResult<spuTDocenteAsignatura_InsertarResult> spuTDocenteAsignatura_Insertar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodDocente_Asignatura", DbType="VarChar(12)")] string codDocente_Asignatura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodDocente", DbType="VarChar(5)")] string codDocente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodAsignatura", DbType="VarChar(12)")] string codAsignatura)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codDocente_Asignatura, codDocente, codAsignatura);
			return ((ISingleResult<spuTDocenteAsignatura_InsertarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spuTLaboratorio_Actualizar")]
		public ISingleResult<spuTLaboratorio_ActualizarResult> spuTLaboratorio_Actualizar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodLaboratorio", DbType="VarChar(12)")] string codLaboratorio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NroLaboratorio", DbType="VarChar(20)")] string nroLaboratorio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codLaboratorio, nroLaboratorio);
			return ((ISingleResult<spuTLaboratorio_ActualizarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spuTLaboratorio_Insertar")]
		public ISingleResult<spuTLaboratorio_InsertarResult> spuTLaboratorio_Insertar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodLaboratorio", DbType="VarChar(12)")] string codLaboratorio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NroLaboratorio", DbType="VarChar(20)")] string nroLaboratorio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codLaboratorio, nroLaboratorio);
			return ((ISingleResult<spuTLaboratorio_InsertarResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TPrincipal")]
	public partial class TPrincipal
	{
		
		private string _CodDocente_Asignatura;
		
		private string _CodLaboratorio;
		
		private string _CodDia;
		
		private string _CodHorario;
		
		public TPrincipal()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodDocente_Asignatura", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string CodDocente_Asignatura
		{
			get
			{
				return this._CodDocente_Asignatura;
			}
			set
			{
				if ((this._CodDocente_Asignatura != value))
				{
					this._CodDocente_Asignatura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodLaboratorio", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string CodLaboratorio
		{
			get
			{
				return this._CodLaboratorio;
			}
			set
			{
				if ((this._CodLaboratorio != value))
				{
					this._CodLaboratorio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodDia", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string CodDia
		{
			get
			{
				return this._CodDia;
			}
			set
			{
				if ((this._CodDia != value))
				{
					this._CodDia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodHorario", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string CodHorario
		{
			get
			{
				return this._CodHorario;
			}
			set
			{
				if ((this._CodHorario != value))
				{
					this._CodHorario = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TUsuario1")]
	public partial class TUsuario1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Usuario;
		
		private string _Contraseña;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnContraseñaChanging(string value);
    partial void OnContraseñaChanged();
    #endregion
		
		public TUsuario1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this.OnContraseñaChanging(value);
					this.SendPropertyChanging();
					this._Contraseña = value;
					this.SendPropertyChanged("Contraseña");
					this.OnContraseñaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAsignatura")]
	public partial class TAsignatura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodAsignatura;
		
		private string _NombreAsignatura;
		
		private string _Creditos;
		
		private string _Categoria;
		
		private EntitySet<TDocente_Asignatura> _TDocente_Asignatura;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodAsignaturaChanging(string value);
    partial void OnCodAsignaturaChanged();
    partial void OnNombreAsignaturaChanging(string value);
    partial void OnNombreAsignaturaChanged();
    partial void OnCreditosChanging(string value);
    partial void OnCreditosChanged();
    partial void OnCategoriaChanging(string value);
    partial void OnCategoriaChanged();
    #endregion
		
		public TAsignatura()
		{
			this._TDocente_Asignatura = new EntitySet<TDocente_Asignatura>(new Action<TDocente_Asignatura>(this.attach_TDocente_Asignatura), new Action<TDocente_Asignatura>(this.detach_TDocente_Asignatura));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodAsignatura", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodAsignatura
		{
			get
			{
				return this._CodAsignatura;
			}
			set
			{
				if ((this._CodAsignatura != value))
				{
					this.OnCodAsignaturaChanging(value);
					this.SendPropertyChanging();
					this._CodAsignatura = value;
					this.SendPropertyChanged("CodAsignatura");
					this.OnCodAsignaturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreAsignatura", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string NombreAsignatura
		{
			get
			{
				return this._NombreAsignatura;
			}
			set
			{
				if ((this._NombreAsignatura != value))
				{
					this.OnNombreAsignaturaChanging(value);
					this.SendPropertyChanging();
					this._NombreAsignatura = value;
					this.SendPropertyChanged("NombreAsignatura");
					this.OnNombreAsignaturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creditos", DbType="VarChar(20)")]
		public string Creditos
		{
			get
			{
				return this._Creditos;
			}
			set
			{
				if ((this._Creditos != value))
				{
					this.OnCreditosChanging(value);
					this.SendPropertyChanging();
					this._Creditos = value;
					this.SendPropertyChanged("Creditos");
					this.OnCreditosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="VarChar(20)")]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this.OnCategoriaChanging(value);
					this.SendPropertyChanging();
					this._Categoria = value;
					this.SendPropertyChanged("Categoria");
					this.OnCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAsignatura_TDocente_Asignatura", Storage="_TDocente_Asignatura", ThisKey="CodAsignatura", OtherKey="CodAsignatura")]
		public EntitySet<TDocente_Asignatura> TDocente_Asignatura
		{
			get
			{
				return this._TDocente_Asignatura;
			}
			set
			{
				this._TDocente_Asignatura.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TDocente_Asignatura(TDocente_Asignatura entity)
		{
			this.SendPropertyChanging();
			entity.TAsignatura = this;
		}
		
		private void detach_TDocente_Asignatura(TDocente_Asignatura entity)
		{
			this.SendPropertyChanging();
			entity.TAsignatura = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TDia")]
	public partial class TDia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodDia;
		
		private string _Dia;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodDiaChanging(string value);
    partial void OnCodDiaChanged();
    partial void OnDiaChanging(string value);
    partial void OnDiaChanged();
    #endregion
		
		public TDia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodDia", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodDia
		{
			get
			{
				return this._CodDia;
			}
			set
			{
				if ((this._CodDia != value))
				{
					this.OnCodDiaChanging(value);
					this.SendPropertyChanging();
					this._CodDia = value;
					this.SendPropertyChanged("CodDia");
					this.OnCodDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dia", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Dia
		{
			get
			{
				return this._Dia;
			}
			set
			{
				if ((this._Dia != value))
				{
					this.OnDiaChanging(value);
					this.SendPropertyChanging();
					this._Dia = value;
					this.SendPropertyChanged("Dia");
					this.OnDiaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TDocente")]
	public partial class TDocente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodDocente;
		
		private string _Nombre;
		
		private EntitySet<TDocente_Asignatura> _TDocente_Asignatura;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodDocenteChanging(string value);
    partial void OnCodDocenteChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public TDocente()
		{
			this._TDocente_Asignatura = new EntitySet<TDocente_Asignatura>(new Action<TDocente_Asignatura>(this.attach_TDocente_Asignatura), new Action<TDocente_Asignatura>(this.detach_TDocente_Asignatura));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodDocente", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodDocente
		{
			get
			{
				return this._CodDocente;
			}
			set
			{
				if ((this._CodDocente != value))
				{
					this.OnCodDocenteChanging(value);
					this.SendPropertyChanging();
					this._CodDocente = value;
					this.SendPropertyChanged("CodDocente");
					this.OnCodDocenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TDocente_TDocente_Asignatura", Storage="_TDocente_Asignatura", ThisKey="CodDocente", OtherKey="CodDocente")]
		public EntitySet<TDocente_Asignatura> TDocente_Asignatura
		{
			get
			{
				return this._TDocente_Asignatura;
			}
			set
			{
				this._TDocente_Asignatura.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TDocente_Asignatura(TDocente_Asignatura entity)
		{
			this.SendPropertyChanging();
			entity.TDocente = this;
		}
		
		private void detach_TDocente_Asignatura(TDocente_Asignatura entity)
		{
			this.SendPropertyChanging();
			entity.TDocente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TDocente_Asignatura")]
	public partial class TDocente_Asignatura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodDocente_Asignatura;
		
		private string _CodDocente;
		
		private string _CodAsignatura;
		
		private EntityRef<TAsignatura> _TAsignatura;
		
		private EntityRef<TDocente> _TDocente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodDocente_AsignaturaChanging(string value);
    partial void OnCodDocente_AsignaturaChanged();
    partial void OnCodDocenteChanging(string value);
    partial void OnCodDocenteChanged();
    partial void OnCodAsignaturaChanging(string value);
    partial void OnCodAsignaturaChanged();
    #endregion
		
		public TDocente_Asignatura()
		{
			this._TAsignatura = default(EntityRef<TAsignatura>);
			this._TDocente = default(EntityRef<TDocente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodDocente_Asignatura", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodDocente_Asignatura
		{
			get
			{
				return this._CodDocente_Asignatura;
			}
			set
			{
				if ((this._CodDocente_Asignatura != value))
				{
					this.OnCodDocente_AsignaturaChanging(value);
					this.SendPropertyChanging();
					this._CodDocente_Asignatura = value;
					this.SendPropertyChanged("CodDocente_Asignatura");
					this.OnCodDocente_AsignaturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodDocente", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string CodDocente
		{
			get
			{
				return this._CodDocente;
			}
			set
			{
				if ((this._CodDocente != value))
				{
					if (this._TDocente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodDocenteChanging(value);
					this.SendPropertyChanging();
					this._CodDocente = value;
					this.SendPropertyChanged("CodDocente");
					this.OnCodDocenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodAsignatura", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string CodAsignatura
		{
			get
			{
				return this._CodAsignatura;
			}
			set
			{
				if ((this._CodAsignatura != value))
				{
					if (this._TAsignatura.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodAsignaturaChanging(value);
					this.SendPropertyChanging();
					this._CodAsignatura = value;
					this.SendPropertyChanged("CodAsignatura");
					this.OnCodAsignaturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAsignatura_TDocente_Asignatura", Storage="_TAsignatura", ThisKey="CodAsignatura", OtherKey="CodAsignatura", IsForeignKey=true)]
		public TAsignatura TAsignatura
		{
			get
			{
				return this._TAsignatura.Entity;
			}
			set
			{
				TAsignatura previousValue = this._TAsignatura.Entity;
				if (((previousValue != value) 
							|| (this._TAsignatura.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAsignatura.Entity = null;
						previousValue.TDocente_Asignatura.Remove(this);
					}
					this._TAsignatura.Entity = value;
					if ((value != null))
					{
						value.TDocente_Asignatura.Add(this);
						this._CodAsignatura = value.CodAsignatura;
					}
					else
					{
						this._CodAsignatura = default(string);
					}
					this.SendPropertyChanged("TAsignatura");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TDocente_TDocente_Asignatura", Storage="_TDocente", ThisKey="CodDocente", OtherKey="CodDocente", IsForeignKey=true)]
		public TDocente TDocente
		{
			get
			{
				return this._TDocente.Entity;
			}
			set
			{
				TDocente previousValue = this._TDocente.Entity;
				if (((previousValue != value) 
							|| (this._TDocente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TDocente.Entity = null;
						previousValue.TDocente_Asignatura.Remove(this);
					}
					this._TDocente.Entity = value;
					if ((value != null))
					{
						value.TDocente_Asignatura.Add(this);
						this._CodDocente = value.CodDocente;
					}
					else
					{
						this._CodDocente = default(string);
					}
					this.SendPropertyChanged("TDocente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THorario")]
	public partial class THorario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodHorario;
		
		private string _Horario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodHorarioChanging(string value);
    partial void OnCodHorarioChanged();
    partial void OnHorarioChanging(string value);
    partial void OnHorarioChanged();
    #endregion
		
		public THorario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodHorario", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodHorario
		{
			get
			{
				return this._CodHorario;
			}
			set
			{
				if ((this._CodHorario != value))
				{
					this.OnCodHorarioChanging(value);
					this.SendPropertyChanging();
					this._CodHorario = value;
					this.SendPropertyChanged("CodHorario");
					this.OnCodHorarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Horario", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Horario
		{
			get
			{
				return this._Horario;
			}
			set
			{
				if ((this._Horario != value))
				{
					this.OnHorarioChanging(value);
					this.SendPropertyChanging();
					this._Horario = value;
					this.SendPropertyChanged("Horario");
					this.OnHorarioChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TLaboratorio")]
	public partial class TLaboratorio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodLaboratorio;
		
		private string _NroLaboratorio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodLaboratorioChanging(string value);
    partial void OnCodLaboratorioChanged();
    partial void OnNroLaboratorioChanging(string value);
    partial void OnNroLaboratorioChanged();
    #endregion
		
		public TLaboratorio()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodLaboratorio", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodLaboratorio
		{
			get
			{
				return this._CodLaboratorio;
			}
			set
			{
				if ((this._CodLaboratorio != value))
				{
					this.OnCodLaboratorioChanging(value);
					this.SendPropertyChanging();
					this._CodLaboratorio = value;
					this.SendPropertyChanged("CodLaboratorio");
					this.OnCodLaboratorioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NroLaboratorio", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NroLaboratorio
		{
			get
			{
				return this._NroLaboratorio;
			}
			set
			{
				if ((this._NroLaboratorio != value))
				{
					this.OnNroLaboratorioChanging(value);
					this.SendPropertyChanging();
					this._NroLaboratorio = value;
					this.SendPropertyChanged("NroLaboratorio");
					this.OnNroLaboratorioChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TPerfil")]
	public partial class TPerfil : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodPerfil;
		
		private string _Perfil;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodPerfilChanging(string value);
    partial void OnCodPerfilChanged();
    partial void OnPerfilChanging(string value);
    partial void OnPerfilChanged();
    #endregion
		
		public TPerfil()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodPerfil", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodPerfil
		{
			get
			{
				return this._CodPerfil;
			}
			set
			{
				if ((this._CodPerfil != value))
				{
					this.OnCodPerfilChanging(value);
					this.SendPropertyChanging();
					this._CodPerfil = value;
					this.SendPropertyChanged("CodPerfil");
					this.OnCodPerfilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Perfil", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Perfil
		{
			get
			{
				return this._Perfil;
			}
			set
			{
				if ((this._Perfil != value))
				{
					this.OnPerfilChanging(value);
					this.SendPropertyChanging();
					this._Perfil = value;
					this.SendPropertyChanged("Perfil");
					this.OnPerfilChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TPerfil_Usuario")]
	public partial class TPerfil_Usuario
	{
		
		private string _CodPerfil;
		
		private string _CodUsuario;
		
		public TPerfil_Usuario()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodPerfil", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string CodPerfil
		{
			get
			{
				return this._CodPerfil;
			}
			set
			{
				if ((this._CodPerfil != value))
				{
					this._CodPerfil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodUsuario", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string CodUsuario
		{
			get
			{
				return this._CodUsuario;
			}
			set
			{
				if ((this._CodUsuario != value))
				{
					this._CodUsuario = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TPrincipal")]
	public partial class TPrincipal1
	{
		
		private string _CodDocente_Asignatura;
		
		private string _CodLaboratorio;
		
		private string _CodDia;
		
		private string _CodHorario;
		
		public TPrincipal1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodDocente_Asignatura", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string CodDocente_Asignatura
		{
			get
			{
				return this._CodDocente_Asignatura;
			}
			set
			{
				if ((this._CodDocente_Asignatura != value))
				{
					this._CodDocente_Asignatura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodLaboratorio", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string CodLaboratorio
		{
			get
			{
				return this._CodLaboratorio;
			}
			set
			{
				if ((this._CodLaboratorio != value))
				{
					this._CodLaboratorio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodDia", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string CodDia
		{
			get
			{
				return this._CodDia;
			}
			set
			{
				if ((this._CodDia != value))
				{
					this._CodDia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodHorario", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string CodHorario
		{
			get
			{
				return this._CodHorario;
			}
			set
			{
				if ((this._CodHorario != value))
				{
					this._CodHorario = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TUsuario")]
	public partial class TUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdUsuario;
		
		private string _Usuario;
		
		private string _Contraseña;
		
		private string _Nombre;
		
		private string _Apellido_Paterno;
		
		private string _Apellido_Materno;
		
		private string _Dni;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdUsuarioChanging(string value);
    partial void OnIdUsuarioChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnContraseñaChanging(string value);
    partial void OnContraseñaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellido_PaternoChanging(string value);
    partial void OnApellido_PaternoChanged();
    partial void OnApellido_MaternoChanging(string value);
    partial void OnApellido_MaternoChanged();
    partial void OnDniChanging(string value);
    partial void OnDniChanged();
    #endregion
		
		public TUsuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this.OnContraseñaChanging(value);
					this.SendPropertyChanging();
					this._Contraseña = value;
					this.SendPropertyChanged("Contraseña");
					this.OnContraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido_Paterno", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Apellido_Paterno
		{
			get
			{
				return this._Apellido_Paterno;
			}
			set
			{
				if ((this._Apellido_Paterno != value))
				{
					this.OnApellido_PaternoChanging(value);
					this.SendPropertyChanging();
					this._Apellido_Paterno = value;
					this.SendPropertyChanged("Apellido_Paterno");
					this.OnApellido_PaternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido_Materno", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Apellido_Materno
		{
			get
			{
				return this._Apellido_Materno;
			}
			set
			{
				if ((this._Apellido_Materno != value))
				{
					this.OnApellido_MaternoChanging(value);
					this.SendPropertyChanging();
					this._Apellido_Materno = value;
					this.SendPropertyChanged("Apellido_Materno");
					this.OnApellido_MaternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dni", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Dni
		{
			get
			{
				return this._Dni;
			}
			set
			{
				if ((this._Dni != value))
				{
					this.OnDniChanging(value);
					this.SendPropertyChanging();
					this._Dni = value;
					this.SendPropertyChanged("Dni");
					this.OnDniChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class spuTDocente_ActualizarResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spuTDocente_ActualizarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(33) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spuTDocente_ListarResult
	{
		
		private string _CodDocente;
		
		private string _Nombre;
		
		public spuTDocente_ListarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodDocente", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string CodDocente
		{
			get
			{
				return this._CodDocente;
			}
			set
			{
				if ((this._CodDocente != value))
				{
					this._CodDocente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}
	
	public partial class spuTDocente_InsertarResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spuTDocente_InsertarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(31) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spuTAsignatura_ActualizarResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spuTAsignatura_ActualizarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(33) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spuTAsignatura_InsertarResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spuTAsignatura_InsertarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(31) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spuTDocenteAsignatura_ActualizarResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spuTDocenteAsignatura_ActualizarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(31) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spuTDocenteAsignatura_InsertarResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spuTDocenteAsignatura_InsertarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(31) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spuTLaboratorio_ActualizarResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spuTLaboratorio_ActualizarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(33) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spuTLaboratorio_InsertarResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spuTLaboratorio_InsertarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(31) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
